### ISSUE TITLE
Import TS files

### ISSUE THREAD

**Issue by pammacdotnet** [filipesabella/vscode-live-p5#10]
Would it be possible to import other `.ts` with external logic, like the Cell constructor in [this example](https://www.youtube.com/watch?v=jxGS3fKPKJA) by The Coding Train??
Example:

```typescript
/// <reference path="node_modules/@types/p5/global.d.ts" /> 
/// <reference path="global.d.ts" /> 
import { Cell } from './cell';   // ???
var sketch = (p: p5) => {
    let x :number = 100;
    let y : number = 100;
    p.setup = ()  => {
        p.createCanvas(p.windowWidth, p.windowHeight);
        let cell = new Cell();
    }
    p.draw = () => {
        p.background(0);
        p.fill(154);
        p.circle(x++, y, 70);
        p.rectMode(p.CENTER)
    }
}
let p5i = new p5(sketch); 
```

And a simple `cell.ts` file:
```typescript
function Cell(){
    this.pos = 40;
}
export { Cell }
```

Thanks in advance.

**Comment by filipesabella** [comment]
Hey there, @pammacdotnet! Apologies for the delay.

TS support is definitely very basic. The compilation of typescript files happens here https://github.com/filipesabella/vscode-live-p5/blob/master/src/extension.ts#L59

In order to support multiple files, it'd be necessary to add a proper build stage, which's possible but outside of the scope for this extension. It's meant mostly as a quick-sketch making tool.

The way you could work around this limitation would be to simply add all the code in the same file. Messy, I know.
