### ISSUE TITLE
Sketches with assets don't work

### ISSUE THREAD

**Issue by rbtcollins** [filipesabella/vscode-live-p5#12]
E.g. fonts, png's that kind of thing. Sample:

```
function preload()
{
	background= loadImage('background.png');
}

function setup()
{
	createCanvas(background.width, background.height);
}

function draw()
{
	image(background, 0, 0);
}

**Comment by rbtcollins** [comment]
```
Access to image at 'file:///...' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https. [file:///C:/...index.html]
```

Turns up in the debug console after a while. I don't know if this extension is invoking a chrome under the hood - if so passing --allow-file-access-from-files should fix it.

**Comment by filipesabella** [comment]
Hey there @rbtcollins, thanks for the report! I'll take a look on the weekend.

**Comment by filipesabella** [comment]
I've spent the last couple of hours trying to find a solution, but I don't think there will be one, @rbtcollins :(

In the end there's this github issue and stackoverflow post, and each point to each other hah
https://stackoverflow.com/questions/55841688/vscode-cross-origin-request-inside-webview
https://github.com/microsoft/vscode/issues/72900

Which kinda makes sense, to not allow a random page in a webview to have file access, but it's a bummer.

Perhaps it'd be possible to make it work if the webview loaded a page from, say, `localhost:1234` instead of simply a file.

**Comment by rbtcollins** [comment]
Perhaps you could layer on the go-live extension? https://github.com/ritwickdey/vscode-live-server Using that works, it is just not embedded in a webview obviously...

**Comment by filipesabella** [comment]
Hey there Collins! Sorry about the delay, I was focussing on [this thing](https://github.com/filipesabella/ProcessingP5) the past couple of weekends.  
  
It has its own live server, so I might feel inclined to port the updates on that to this extension. However, if you're feeling really inspired, a PR would be a m a z i n g.

**Comment by olgv** [comment]
Unable to preview loading a 3d model. Might be relevant for this thread. Thank you.

**Comment by filipesabella** [comment]
Thanks for the report @olgv.

The problem is still the same: it's a lot of work to port the server code from ProcessingP5 to this extension, and it's bug prone, full-of-corner-cases kinda code.

Until that perhaps eventually gets done, you can use ProcessingP5 with the option to edit code in your own editor, vscode in this case, so you get the auto refresh stuff with loading of files working.
