### ISSUE TITLE
Problem with classes in other files

### ISSUE THREAD

**Issue by Drarig29** [filipesabella/vscode-live-p5#3]
I created a new JS file with a class in it. But when I start using this class (just instantiating it) in my main sketch file, graphics are not shown anymore.

First I opened the live panel from the sketch file, but it didn't work so I've tried opening it from the index.html (so that it'd have had the reference to my other file) but it doesn't work neither.

PS: my code works perfectly on any browser, but not on your live window, so that's not the thing.

**Comment by Drarig29** [comment]
For now, I moved my class to my sketch file, but it's messy, I like to have different files... ^^

**Comment by filipesabella** [comment]
Hey @Drarig29 thanks for the report.

Because of the way the plugin is designed, multiple files are not going to work as you intended.

A new `index.html` is created on the fly and opened in the vscode view. You can see how the template is generated here:
https://github.com/filipesabella/vscode-live-p5/blob/master/src/TextDocumentContentProvider.ts

Because of that, new files won't be included.


I was thinking about a way to enable users to provide their own `index.html`, but haven't committed to any designs yet. Suggestions are welcome.

**Comment by Drarig29** [comment]
Ok I'll see this later, I'll think of it ;)

**Comment by filipesabella** [comment]
@Drarig29 thanks again for the report, I'll be glad to fix any other issues you might find.

**Comment by wejust1027** [comment]
Hey @filipesabella . I really like to use live-p5 you developed, but now VSCODE-P5canvas has adopted the new WebView API, live-p5 can not run, please check if there is an update, thank you!
